<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class UnitTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('unit')->insert([
            [
                'unitCode' => 'HIT3315',
                'unitName' => 'Languages in Software Development',
                'minimumCompletedUnits' => '0',
                'maxStudentCount' => 100,
                'lectureGroupCount' => 10,
                'lectureDuration' => '2h',
                'tutorialGroupCount' => 10,
                'tutorialDuration' => '2h',
                'unitInfo' => '[{"convenor":"kikuji"},{"lecturers":["kakuji"],"lecturers_count":1},{"tutors":["kossen"],"tutors_count":1}]',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'unitCode' => 'HIT3158',
                'unitName' => 'Software Engineering Project A',
                'minimumCompletedUnits' => '0',
                'maxStudentCount' => 100,
                'lectureGroupCount' => 10,
                'lectureDuration' => '2h',
                'tutorialGroupCount' => 10,
                'tutorialDuration' => '2h',
                'unitInfo' => '[{"convenor":"kikuji"},{"lecturers":["kakuji"],"lecturers_count":1},{"tutors":["kossen"],"tutors_count":1}]',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'unitCode' => 'HIT3310',
                'unitName' => 'Software Architecture and Design',
                'minimumCompletedUnits' => '0',
                'maxStudentCount' => 100,
                'lectureGroupCount' => 10,
                'lectureDuration' => '2h',
                'tutorialGroupCount' => 10,
                'tutorialDuration' => '2h',
                'unitInfo' => '[{"convenor":"kikuji"},{"lecturers":["kakuji"],"lecturers_count":1},{"tutors":["kossen"],"tutors_count":1}]',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'unitCode' => 'HIT1234',
                'unitName' => 'Internet Technologies',
                'minimumCompletedUnits' => '0',
                'maxStudentCount' => 100,
                'lectureGroupCount' => 10,
                'lectureDuration' => '2h',
                'tutorialGroupCount' => 10,
                'tutorialDuration' => '2h',
                'unitInfo' => '[{"convenor":"kikuji"},{"lecturers":["kakuji"],"lecturers_count":1},{"tutors":["kossen"],"tutors_count":1}]',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'unitCode' => 'HIT1235',
                'unitName' => 'Web Programming',
                'minimumCompletedUnits' => '0',
                'maxStudentCount' => 100,
                'lectureGroupCount' => 10,
                'lectureDuration' => '2h',
                'tutorialGroupCount' => 10,
                'tutorialDuration' => '2h',
                'unitInfo' => '[{"convenor":"kikuji"},{"lecturers":["kakuji"],"lecturers_count":1},{"tutors":["kossen"],"tutors_count":1}]',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'unitCode' => 'MGT10001',
                'unitName' => 'Introduction to Management',
                'minimumCompletedUnits' => '0',
                'maxStudentCount' => 100,
                'lectureGroupCount' => 10,
                'lectureDuration' => '2h',
                'tutorialGroupCount' => 10,
                'tutorialDuration' => '2h',
                'unitInfo' => '[{"convenor":"kikuji"},{"lecturers":["kakuji"],"lecturers_count":1},{"tutors":["kossen"],"tutors_count":1}]',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'unitCode' => 'ACC10007',
                'unitName' => 'Management Accounting',
                'minimumCompletedUnits' => '0',
                'maxStudentCount' => 100,
                'lectureGroupCount' => 10,
                'lectureDuration' => '2h',
                'tutorialGroupCount' => 10,
                'tutorialDuration' => '2h',
                'unitInfo' => '[{"convenor":"kikuji"},{"lecturers":["kakuji"],"lecturers_count":1},{"tutors":["kossen"],"tutors_count":1}]',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'unitCode' => 'ACC10008',
                'unitName' => 'Management Accounting B',
                'minimumCompletedUnits' => '0',
                'maxStudentCount' => 100,
                'lectureGroupCount' => 10,
                'lectureDuration' => '2h',
                'tutorialGroupCount' => 10,
                'tutorialDuration' => '2h',
                'unitInfo' => '[{"convenor":"kikuji"},{"lecturers":["kakuji"],"lecturers_count":1},{"tutors":["kossen"],"tutors_count":1}]',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'unitCode' => 'UNI20',
                'unitName' => 'A Unit With Many MinimumCompletedUnits',
                'minimumCompletedUnits' => '20',
                'maxStudentCount' => 100,
                'lectureGroupCount' => 10,
                'lectureDuration' => '2h',
                'tutorialGroupCount' => 10,
                'tutorialDuration' => '2h',
                'unitInfo' => '[{"convenor":"kikuji"},{"lecturers":["kakuji"],"lecturers_count":1},{"tutors":["kossen"],"tutors_count":1}]',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'unitCode' => 'UNI2',
                'unitName' => 'A Unit With Few MinimumCompletedUnits',
                'minimumCompletedUnits' => '2',
                'maxStudentCount' => 100,
                'lectureGroupCount' => 10,
                'lectureDuration' => '2h',
                'tutorialGroupCount' => 10,
                'tutorialDuration' => '2h',
                'unitInfo' => '[{"convenor":"kikuji"},{"lecturers":["kakuji"],"lecturers_count":1},{"tutors":["kossen"],"tutors_count":1}]',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'unitCode' => 'COR30',
                'unitName' => 'A Unit With Corequisite',
                'minimumCompletedUnits' => '0',
                'maxStudentCount' => 100,
                'lectureGroupCount' => 10,
                'lectureDuration' => '2h',
                'tutorialGroupCount' => 10,
                'tutorialDuration' => '2h',
                'unitInfo' => '[{"convenor":"kikuji"},{"lecturers":["kakuji"],"lecturers_count":1},{"tutors":["kossen"],"tutors_count":1}]',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'unitCode' => 'COR01',
                'unitName' => 'Unit Taken With Corequisite',
                'minimumCompletedUnits' => '0',
                'maxStudentCount' => 100,
                'lectureGroupCount' => 10,
                'lectureDuration' => '2h',
                'tutorialGroupCount' => 10,
                'tutorialDuration' => '2h',
                'unitInfo' => '[{"convenor":"kikuji"},{"lecturers":["kakuji"],"lecturers_count":1},{"tutors":["kossen"],"tutors_count":1}]',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'unitCode' => 'SHO27',
                'unitName' => 'Short Semester Unit',
                'minimumCompletedUnits' => '0',
                'maxStudentCount' => 100,
                'lectureGroupCount' => 10,
                'lectureDuration' => '2h',
                'tutorialGroupCount' => 10,
                'tutorialDuration' => '2h',
                'unitInfo' => '[{"convenor":"kikuji"},{"lecturers":["kakuji"],"lecturers_count":1},{"tutors":["kossen"],"tutors_count":1}]',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'unitCode' => 'FO1',
                'unitName' => 'Foundation Unit 1',
                'minimumCompletedUnits' => '0',
                'maxStudentCount' => 100,
                'lectureGroupCount' => 10,
                'lectureDuration' => '2h',
                'tutorialGroupCount' => 10,
                'tutorialDuration' => '2h',
                'unitInfo' => '[{"convenor":"kikuji"},{"lecturers":["kakuji"],"lecturers_count":1},{"tutors":["kossen"],"tutors_count":1}]',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'unitCode' => 'FO2',
                'unitName' => 'Foundation Unit 2',
                'minimumCompletedUnits' => '0',
                'maxStudentCount' => 100,
                'lectureGroupCount' => 10,
                'lectureDuration' => '2h',
                'tutorialGroupCount' => 10,
                'tutorialDuration' => '2h',
                'unitInfo' => '[{"convenor":"kikuji"},{"lecturers":["kakuji"],"lecturers_count":1},{"tutors":["kossen"],"tutors_count":1}]',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'unitCode' => 'HIT1312',
                'unitName' => 'Computer and Logic Essentials',
                'minimumCompletedUnits' => '0',
                'maxStudentCount' => 100,
                'lectureGroupCount' => 10,
                'lectureDuration' => '2h',
                'tutorialGroupCount' => 10,
                'tutorialDuration' => '2h',
                'unitInfo' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'unitCode' => 'HIT2080',
                'unitName' => 'Introduction to Programming',
                'minimumCompletedUnits' => '0',
                'maxStudentCount' => 100,
                'lectureGroupCount' => 10,
                'lectureDuration' => '2h',
                'tutorialGroupCount' => 10,
                'tutorialDuration' => '2h',
                'unitInfo' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'unitCode' => 'HIT2120',
                'unitName' => 'Data Communications and Security',
                'minimumCompletedUnits' => '0',
                'maxStudentCount' => 100,
                'lectureGroupCount' => 10,
                'lectureDuration' => '2h',
                'tutorialGroupCount' => 10,
                'tutorialDuration' => '2h',
                'unitInfo' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'unitCode' => 'HIT1402',
                'unitName' => 'Database Analysis and Design',
                'minimumCompletedUnits' => '0',
                'maxStudentCount' => 100,
                'lectureGroupCount' => 10,
                'lectureDuration' => '2h',
                'tutorialGroupCount' => 10,
                'tutorialDuration' => '2h',
                'unitInfo' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'unitCode' => 'HIT1307',
                'unitName' => 'Internet Technologies',
                'minimumCompletedUnits' => '0',
                'maxStudentCount' => 100,
                'lectureGroupCount' => 10,
                'lectureDuration' => '2h',
                'tutorialGroupCount' => 10,
                'tutorialDuration' => '2h',
                'unitInfo' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'unitCode' => 'HIT3172',
                'unitName' => 'Object-Oriented Programming in C++',
                'minimumCompletedUnits' => '0',
                'maxStudentCount' => 100,
                'lectureGroupCount' => 10,
                'lectureDuration' => '2h',
                'tutorialGroupCount' => 10,
                'tutorialDuration' => '2h',
                'unitInfo' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'unitCode' => 'HIT3181',
                'unitName' => 'Technical Software Development',
                'minimumCompletedUnits' => '0',
                'maxStudentCount' => 100,
                'lectureGroupCount' => 10,
                'lectureDuration' => '2h',
                'tutorialGroupCount' => 10,
                'tutorialDuration' => '2h',
                'unitInfo' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'unitCode' => 'HIT3309',
                'unitName' => 'Software Project Practices and Management',
                'minimumCompletedUnits' => '0',
                'maxStudentCount' => 100,
                'lectureGroupCount' => 10,
                'lectureDuration' => '2h',
                'tutorialGroupCount' => 10,
                'tutorialDuration' => '2h',
                'unitInfo' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'unitCode' => 'HIT2312',
                'unitName' => 'Computer Systems',
                'minimumCompletedUnits' => '0',
                'maxStudentCount' => 100,
                'lectureGroupCount' => 10,
                'lectureDuration' => '2h',
                'tutorialGroupCount' => 10,
                'tutorialDuration' => '2h',
                'unitInfo' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'unitCode' => 'HIT2308',
                'unitName' => 'Software Development Practices',
                'minimumCompletedUnits' => '0',
                'maxStudentCount' => 100,
                'lectureGroupCount' => 10,
                'lectureDuration' => '2h',
                'tutorialGroupCount' => 10,
                'tutorialDuration' => '2h',
                'unitInfo' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'unitCode' => 'HIT2316',
                'unitName' => 'Usability',
                'minimumCompletedUnits' => '0',
                'maxStudentCount' => 100,
                'lectureGroupCount' => 10,
                'lectureDuration' => '2h',
                'tutorialGroupCount' => 10,
                'tutorialDuration' => '2h',
                'unitInfo' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'unitCode' => 'HIT3044',
                'unitName' => 'Professional Issues in IT',
                'minimumCompletedUnits' => '12',
                'maxStudentCount' => 100,
                'lectureGroupCount' => 10,
                'lectureDuration' => '2h',
                'tutorialGroupCount' => 10,
                'tutorialDuration' => '2h',
                'unitInfo' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'unitCode' => 'HIT3311',
                'unitName' => 'Software Deployment and Evolution',
                'minimumCompletedUnits' => '0',
                'maxStudentCount' => 100,
                'lectureGroupCount' => 10,
                'lectureDuration' => '2h',
                'tutorialGroupCount' => 10,
                'tutorialDuration' => '2h',
                'unitInfo' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'unitCode' => 'HIT3258',
                'unitName' => 'Software Engineering Project B',
                'minimumCompletedUnits' => '0',
                'maxStudentCount' => 100,
                'lectureGroupCount' => 10,
                'lectureDuration' => '2h',
                'tutorialGroupCount' => 10,
                'tutorialDuration' => '2h',
                'unitInfo' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'unitCode' => 'HIT3002',
                'unitName' => 'Introduction to Artificial Intelligence',
                'minimumCompletedUnits' => '0',
                'maxStudentCount' => 100,
                'lectureGroupCount' => 10,
                'lectureDuration' => '2h',
                'tutorialGroupCount' => 10,
                'tutorialDuration' => '2h',
                'unitInfo' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'unitCode' => 'HIT3037',
                'unitName' => 'Programming in Java',
                'minimumCompletedUnits' => '0',
                'maxStudentCount' => 100,
                'lectureGroupCount' => 10,
                'lectureDuration' => '2h',
                'tutorialGroupCount' => 10,
                'tutorialDuration' => '2h',
                'unitInfo' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'unitCode' => 'COS20007',
                'unitName' => 'OBJECT-ORIENTED PROGRAMMING',
                'minimumCompletedUnits' => '0',
                'maxStudentCount' => 100,
                'lectureGroupCount' => 10,
                'lectureDuration' => '2h',
                'tutorialGroupCount' => 10,
                'tutorialDuration' => '2h',
                'unitInfo' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'unitCode' => 'HIT1401',
                'unitName' => 'Introduction to Business Information Systems',
                'minimumCompletedUnits' => '0',
                'maxStudentCount' => 100,
                'lectureGroupCount' => 10,
                'lectureDuration' => '2h',
                'tutorialGroupCount' => 10,
                'tutorialDuration' => '2h',
                'unitInfo' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ]
        ]);
    }
}
