@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <!-- Reserve 3 space for navigation column -->
        <div class="col-md-3">
            <div class="list-group">
                <a href="{{ url('/student') }}" class="list-group-item">Enrolment Status</a>
                <a href="{{ url('/student/enrolmenthistory') }}" class="list-group-item">Enrolment History</a>
                <a href="{{ url('/student/manageunits/create') }}" class="list-group-item">Manage Units</a>
                <a href="{{ url('/student/viewstudyplanner') }}" class="list-group-item">View Study Planner</a>
                <a href="{{ url('/student/viewunitlistings') }}" class="list-group-item">View Unit Listings</a>
                <a href="{{ url('/student/internalcoursetransfer/create') }}" class="list-group-item">Internal Course Transfer</a>
                <a href="{{ url('/student/enrolmentissues') }}" class="list-group-item active">Other Enrolment Issues</a>
            </div>
        </div>

        <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h1>Contact Course Coordinator <small>for Enrolment Issues</small></h1>
                </div>

                <div class="panel-body">
                    <form class="form-horizontal" name="cForm" role="form" action="{{ url('/student/contactcoordinator') }}" onsubmit="return validateForm()" method="POST">
                        <div class="form-group">
                          <label class="control-label col-sm-2" for="name">Name:</label>
                            <div class="col-sm-10">
                            <input type="text" name="sName" class="form-control" placeholder="John Doe 1000001" disabled>
                        </div>

                        </div>
                        <div class="form-group">
                          <label class="control-label col-sm-2">Title:</label>
                          <div class="col-sm-10">
                              <select class="form-control">
                                  <option value="exemption">Application for Advanced Standing (Exemptions)</option>
                                  <option value="leaveOfAbsence">Application for Leave of Absence</option>
                                  <option value="singleStudyUnit">Application for Single Unit Of Study</option>
                                  <option value="deferanOffer">Application to Defer an Offer (Locals Only)</option>
                                  <option value="enrolByProxy">Application to Enrol by Proxy (Locals Only)</option>
                                  <option value="programWithdrawal">Application Withdrawal from Program</option>
                                  <option value="timetableClash">Form for Student with Irreconcilable Timetable Clashes</option>
                                  <option value="others">Others (None of the above)</option>
                              </select>
                          </div>
                        </div>

                        <!-- This area will be generated by JS to determine what kind of forms needed -->
                        <!-- if none of the above, show the basic content box
                        <div class="form-group">
                            <label class="control-label col-sm-2">Content: </label>
                            <div class="col-sm-10">
                                <textarea class="form-control custom-control" name="cName" rows="3" style="resize:none"></textarea>
                            </div>
                        </div>
                         -->
                        <div class="form-group">
                            <label class="control-label col-sm-2">Course Coordinator: </label>
                            <div class="dropdown col-sm-10">
                                <!-- populate this from database -->
                                <!-- only list out coordinators from the course -->
                                <select class="form-control">
                                    <option value="khsim">Sim Kwan Hua (khsim@swinburne.edu.my)</option>
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-default">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@section('extra_js')
<script>

</script>
@stop
